services:
  jenkins:
    build: .
    env_file:
      - jenkins.env
    volumes:
      - ./my_marvin.yml:/var/jenkins_casc.yml
      - ./job_dsl.groovy:/data/job_dsl.groovy
    ports:
      - "8080:8080"

